server:
  port: 9090


resource_id: classmanagementservice
spring:
  mvc:
    format:
      date: iso
  datasource:
    username: olive
    url: jdbc:mysql://mysql-server:3306/classmanagementDb
    password: yx7oZA9QpomHBWnh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization-server:9092/.well-known/jwks.json
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE